packageExtensions:
  '@graphql-mesh/config@*':
    dependencies:
      fetchache: '*'
  '@graphql-mesh/grpc@*':
    dependencies:
      long: '*'
  '@graphql-mesh/store@*':
    dependencies:
      '@graphql-mesh/types': '*'
  '@graphql-mesh/types@*':
    dependencies:
      '@graphql-mesh/store': '*'
  '@graphql-tools/stitch@*':
    dependencies:
      graphql: '*'
  '@nestjs/common@*':
    dependencies:
      '@grpc/proto-loader': '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/grpc-js': '*'
  '@nestjs/testing@*':
    dependencies:
      '@nestjs/platform-express': '*'
  '@octokit/auth-oauth-user@*':
    dependencies:
      universal-user-agent: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  graphql-ws@*:
    dependencies:
      ws: '*'
  typeorm@*:
    dependencies:
      sql.js: '*'
      sqlite3: '*'
  typesense@*:
    dependencies:
      '@babel/runtime': '*'
  apollo-server-types@*:
    dependencies:
      graphql: '*'
  apollo-server-errors@*:
    dependencies:
      graphql: '*'
  apollo-server-core@*:
    dependencies:
      graphql: '*'
  apollo-graphql@*:
    dependencies:
      graphql: '*'
  '@graphql-tools-utils@*':
    dependencies:
      graphql: '*'

plugins:
  - .yarn/plugins/@atls/plugin-essentials.cjs
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-3.0.2.cjs
