defaultSemverRangePrefix: ''

enableGlobalCache: true

globalFolder: ../.yarn/berry

packageExtensions:
  '@nestjs/testing@*':
    dependencies:
      '@nestjs/platform-express': '*'

pnpEnableEsmLoader: true

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.mjs
