packageExtensions:
  '@graphql-mesh/config@*':
    dependencies:
      fetchache: '*'
  '@graphql-mesh/grpc@*':
    dependencies:
      long: '*'
  '@graphql-mesh/store@*':
    dependencies:
      '@graphql-mesh/types': '*'
  '@graphql-mesh/types@*':
    dependencies:
      '@graphql-mesh/store': '*'
  '@graphql-tools/stitch@*':
    dependencies:
      graphql: '*'
  '@grpc/grpc-js@*':
    dependencies:
      '@types/long': '*'
  '@nestjs/common@*':
    dependencies:
      '@grpc/proto-loader': '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/grpc-js': '*'
  '@nestjs/testing@*':
    dependencies:
      '@nestjs/platform-express': '*'
  '@octokit/auth-oauth-user@*':
    dependencies:
      universal-user-agent: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  graphql-ws@*:
    dependencies:
      ws: '*'
  typesense@*:
    dependencies:
      '@babel/runtime': '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20221107.hash-d21b699.cjs
