enableGlobalCache: true

globalFolder: ../.yarn/berry

packageExtensions:
  '@graphql-mesh/config@*':
    dependencies:
      fetchache: '*'
  '@graphql-mesh/grpc@*':
    dependencies:
      long: '*'
  '@graphql-mesh/store@*':
    dependencies:
      '@graphql-mesh/types': '*'
  '@graphql-mesh/types@*':
    dependencies:
      '@graphql-mesh/store': '*'
  '@graphql-tools/stitch@*':
    dependencies:
      graphql: '*'
  '@grpc/grpc-js@*':
    dependencies:
      '@types/long': '*'
  '@nestjs/common@*':
    dependencies:
      '@grpc/proto-loader': '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/grpc-js': '*'
  '@nestjs/testing@*':
    dependencies:
      '@nestjs/platform-express': '*'
  '@octokit/auth-oauth-user@*':
    dependencies:
      universal-user-agent: '*'
  '@ory/keto-grpc-client@*':
    peerDependencies:
      grpc: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  graphql-ws@*:
    dependencies:
      ws: '*'
  typesense@*:
    dependencies:
      '@babel/runtime': '*'

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn.cjs
