enableGlobalCache: true

globalFolder: ../.yarn/berry

packageExtensions:
  '@nestjs/common@*':
    dependencies:
      '@grpc/proto-loader': '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
  '@nestjs/testing@*':
    dependencies:
      '@nestjs/platform-express': '*'

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn.cjs

preferReuse: true

defaultSemverRangePrefix: ''
