defaultSemverRangePrefix: ''

enableGlobalCache: true

globalFolder: ../.yarn/berry

npmRegistryServer: 'https://registry.npmjs.org'

npmScopes:
  atls:
    npmRegistryServer: 'https://registry.npmjs.org'

packageExtensions:
  '@nestjs/testing@*':
    dependencies:
      '@nestjs/platform-express': '*'
  '@atls/nestjs-validation@*':
    dependencies:
      '@types/node': '22.5.5'

pnpEnableEsmLoader: true

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.mjs
