packageExtensions:
  '@graphql-tools/stitch@*':
    dependencies:
      graphql: '*'
  '@octokit/auth-oauth-user@*':
    dependencies:
      universal-user-agent: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  '@nestjs/graphql@*':
    dependencies:
      graphql: '*'
      apollo-server-core: '2.24.0'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
  '@nestjs/testing@*':
    dependencies:
      '@nestjs/platform-express': '*'
  '@nestjs/common@*':
    dependencies:
      '@grpc/proto-loader': '*'
      rxjs: 6.6.7
  '@nestjs/microservices@*':
    dependencies:
      grpc: '*'
  '@graphql-mesh/grpc@*':
    dependencies:
      long: '*'
  'typeorm@*':
    dependencies:
      'sql.js': '*'
  apollo-reporting-protobuf@*:
    dependencies:
      long: '*'

plugins:
  - .yarn/plugins/@atls/plugin-essentials.cjs
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-berry.cjs
