defaultSemverRangePrefix: ''

enableGlobalCache: true

globalFolder: ../.yarn/berry

npmRegistryServer: 'https://registry.npmjs.org'

npmScopes:
  atls:
    npmRegistryServer: 'https://registry.npmjs.org'

packageExtensions:
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/grpc-js': '*'
      '@grpc/proto-loader': '*'
  '@nestjs/testing@*':
    dependencies:
      '@nestjs/platform-express': '*'

pnpEnableEsmLoader: true

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.mjs
