enableGlobalCache: true

globalFolder: ../.yarn/berry

packageExtensions:
  '@nestjs/common@*':
    dependencies:
      '@grpc/proto-loader': '*'
  '@nestjs/core@*':
    dependencies:
      '@nestjs/platform-express': '*'
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/grpc-js': '*'
  '@nestjs/testing@*':
    dependencies:
      '@nestjs/platform-express': '*'
  '@octokit/auth-oauth-user@*':
    dependencies:
      universal-user-agent: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  typesense@*:
    dependencies:
      '@babel/runtime': '*'

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn.cjs

preferReuse: true

defaultSemverRangePrefix: ''
