export const BATCH_QUEUE_MODULE_OPTIONS = Symbol('BATCH_QUEUE_MODULE_OPTIONS')
export const BATCH_QUEUE_CONSUMER = Symbol('BATCH_QUEUE_CONSUMER')
export const BATCH_QUEUE_PRODUCER = Symbol('BATCH_QUEUE_PRODUCER')
export const BATCH_QUEUE_CHECKER = Symbol('BATCH_QUEUE_CHECKER')
