name: Feature
description: Изменение несущее новые возможности
title: '[Feature] '
type: 'feature'
assignees:
  - TorinAsakura
body:
  - type: input
    id: motivation
    attributes:
      label: С чем связан запрос?
      placeholder: Подумай, а нужна ли вообще таска
    validations:
      required: true

  - type: textarea
    id: plan
    attributes:
      label: Опиши план реализации
      placeholder: Расскажи в паре предложений как ты это будешь реализовывать
    validations:
      required: true

  - type: textarea
    id: dod
    attributes:
      label: Критерии готовности выполнения задачи
      placeholder: |
        По каким критериям оцениваем готовность задачи, например:
        - инициализация:
          - приложение работает в среде
        - работа с данными:
          - на входе - JSON объект товара
          - на выходе - JSON объект товара с ценой в другой валюте
        - Артефакты:
          - запись в лог
    validations:
      required: true
