name: Management
description: Management work
title: '[Management] '
type: 'Management'
assignees:
  - TorinAsakura
body:
  - type: input
    id: motivation
    attributes:
      label: What are we doing?
    validations:
      required: true

  - type: textarea
    id: subj
    attributes:
      label: What will change?
    validations:
      required: true
