name: OPS
description: Operations Tasks
title: "[OPS] "
type: OPS
assignees:
  - TorinAsakura
body:
  - type: dropdown
    id: infra_segment
    attributes:
      label: Infrastructure segment
      options:
        - GitHub
        - Pipelines
        - Kubernetes
        - Infra (PSQL, Pub/Sub, other)
        - MLOps
        - IaC (Terraform, Ansible)
        - GitOps (FluxCD)
        - Networking (Calico, CNI)
        - Observability (Prometheus, Loki, Tempo, Grafana)
        - Security (RBAC, Secrets mgmt)
        - Storage (S3, GCS, PVC)
    validations:
      required: true

  - type: textarea
    id: specs
    attributes:
      label: What are we doing?
      placeholder: Briefly describe the task and the required state
    validations:
      required: true
