export const METHOD_DECORATOR_KEY = Symbol('METHOD_DECORATOR_KEY')

export const STREAM_METHOD_DECORATOR_KEY = Symbol('STREAM_METHOD_DECORATOR_KEY')

export const CONNECTRPC_TRANSPORT = Symbol('CONNECTRPC_TRANSPORT')
