export const OATHKEEPER_API = 'OATHKEEPER_API'
export const OATHKEEPER_MODULE_OPTIONS = 'OATHKEEPER_MODULE_OPTIONS'

export const OATHKEEPER_AUTHORIZATION_HEADER = 'authorization'
export const OATHKEEPER_USER_HEADER = 'x-user'

export const OATHKEEPER_DEFAULT_RESPONSE_HEADERS = [
  OATHKEEPER_AUTHORIZATION_HEADER,
  OATHKEEPER_USER_HEADER,
]
