name: Checks

on: [pull_request]

jobs:
  check:
    name: Typecheck, lint
    uses: atls/shared/.github/workflows/checks.yaml@master
    permissions: write-all
  release:
    name: Release
    uses: atls/shared/.github/workflows/release.yaml@master
    permissions: write-all
  test:
    name: Tests
    uses: atls/shared/.github/workflows/tests.yaml@master
    permissions: write-all
