name: Checks

on:
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  check:
    name: Checks
    if: github.event.pull_request.merged == false && github.event.action != 'closed'
    uses: atls/shared/.github/workflows/checks.yaml@master
    permissions: write-all
