name: Publishing

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure GPG Key
        run: |
          mkdir -p ~/.gnupg/
          printf "$GPG_SIGNING_KEY" | base64 --decode > ~/.gnupg/private.key
          gpg --import ~/.gnupg/private.key
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Configure Git
        run: |
          git config --global user.email $GIT_EMAIL
          git config --global user.name $GIT_USER
          git config --global user.signingkey $GPG_KEY_ID
          git config --global commit.gpgsign true
        env:
          GIT_USER: ${{ secrets.GIT_USER }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

      - name: Install Dependencies
        run: yarn

      - name: Create Release
        run: yarn lerna version --yes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Config NPM
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: Publish to NPM
        run: yarn lerna publish from-package --no-verify-access --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Config GPR
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com/
          scope: ${{ secrets.SCOPE }}

      - name: Publish to GPR
        run: yarn lerna publish from-package --no-verify-access --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
