name: Publish to registry

on:
  pull_request:
    types:
      - closed
    branches:
      - master
    paths-ignore:
      - '.github/**'

jobs:
  publish:
    if: github.event.pull_request.merged == true
    name: Publish
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      YARN_PATH: .yarn/releases/raijin-yarn-1.3.3.mjs

    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.ATLANTIS_SUPER_BOT_APP_ID }}
          private-key: ${{ secrets.ATLANTIS_SUPER_BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: master
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "dir=$(node "$YARN_PATH" config get cacheFolder)" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@v5
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: node "$YARN_PATH" install --inline-builds

      - name: List changed workspaces
        run: node "$YARN_PATH" workspaces changed list --json

      - name: Defer versions
        run: node "$YARN_PATH" release version defer
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Version
        run: node "$YARN_PATH" version apply --all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug git diff
        run: |
          git diff

      - name: Changelog
        if: ${{ !cancelled() }}
        run: node "$YARN_PATH" workspaces changed foreach -v --no-private --exclude . changelog generate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug git diff
        run: |
          git diff

      - name: Release
        if: ${{ !cancelled() }}
        run: node "$YARN_PATH" workspaces changed foreach -v --no-private --exclude . release create
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Npm Publish
        if: ${{ !cancelled() }}
        run: node "$YARN_PATH" workspaces changed foreach -v --no-private --exclude . npm publish --tolerate-republish --access public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: https://registry.npmjs.org
          YARN_NPM_PUBLISH_REGISTRY: https://registry.npmjs.org

      - name: Compose commit message
        if: ${{ !cancelled() }}
        id: commit_message
        run: |
          INITIAL_MESSAGE=$'chore(common): versions\n\n'
          temp_file=$(mktemp)
          node "$YARN_PATH" workspaces changed foreach -v --exclude . exec "printf '%s:%s ' \"\$npm_package_name\" \"\$npm_package_version\" >> \"$temp_file\""
          MESSAGE=$(cat "$temp_file")
          cat "$temp_file"
          INITIAL_MESSAGE+=$MESSAGE
          INITIAL_MESSAGE="${INITIAL_MESSAGE//'%'/' '}"
          INITIAL_MESSAGE="${INITIAL_MESSAGE//$'\n'/' '}"
          INITIAL_MESSAGE="${INITIAL_MESSAGE//$'\r'/' '}"
          echo "commitMessage=$INITIAL_MESSAGE" >> "$GITHUB_OUTPUT"
          echo "$INITIAL_MESSAGE"
          rm "$temp_file"

      - name: Stage all changelog files
        if: ${{ !cancelled() }}
        run: |
          git add '*.md'

      - name: Commit changes
        if: ${{ !cancelled() }}
        uses: planetscale/ghcommit-action@v0.2.20
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          repo: ${{ github.repository }}
          branch: master
          commit_message: ${{ steps.commit_message.outputs.commitMessage }}
          file_pattern: '*.json *.md *.yaml *.yml *.lock'
