name: Version

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  run:
    name: Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.10'

      - name: Install
        run: yarn install
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Changes
        run: yarn files changed list
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Version
        run: yarn workspaces changed foreach --no-private --verbose version patch --deferred
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'chore(common): versions'
          branch: master
