name: Version

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  run:
    name: Publish
    uses: atls/shared/.github/workflows/version.yaml@master
    permissions: write-all
